Just a bump version to "force" a re-download/re-install of VariantAnnotation on the user machines. This will eliminate the following error they get right now when they load the package if it was installed before the split() generic and methods moved from IRanges to S4Vectors:
  Error : object ‘split’ is not exported by 'namespace:IRanges'
  Error: package or namespace load failed for ‘VariantAnnotation’


git-svn-id: https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/VariantAnnotation@109133 bc3139a8-67e5-0310-9ffc-ced21a209358